language: go
go:
  - 1.5

env:
  global:
    - PATH="$GOPATH/bin:$PATH"
    - RELEASES_PATH=/tmp/releases

script:
  - go test -v

before_deploy:
  - go get github.com/laher/goxc
  - goxc -tasks 'xc archive' -bc 'windows darwin linux' -d "$RELEASES_PATH" -resources-include 'README*'

deploy:
  provider: releases
  api_key:
    secure: ATQ2kD8pFLy4DjewIv6zuZJPi3kMdY0bxf+vhQGBe+RPyVR3yU/1azfYX6b2S7Wys73dEotWdjEONXT9KnIzGR8fGgKcWPW5j0fxFsFhKsRpefTAonRpJCleSnABhRWXoWk71RrFQTwEb9Had0+5qMWzKtXMUIu0VITC3atavcaetFKLgLLeIWI5lcbBvy3BDWz37/DlqZJsNhtI9ghApSIZ5mBEUo3TGOrqvxKgMzOqbupJElIovxtpDOEBHFLa0taP5n51LrJ3bGksltRZVyKB+/uWmZp/imZkRzugsQ0GOJfi27hChfzhC/sExcrt0sn7lPswbHcXuzEFDhz6wMMUyYkJm4Qoua4/VPNH2db23JeHyULjA+9il/mYefqQg+Gwg9fuyMgJIv5+UcNc/PyKXJBdR5tGNHOq6fXhkuWxE6uib/WpcMC4jelL+i28UBrSJemzzPJIDHI1nJPu9uwK3OeKp/aXZQq794bzFTLgRrs4g43GQIbLA8rD5jTDeaG9e/bHRqXDRPJhpnbDDJTpjZbzOCJOfUJ4nmDshnRrhMAgalatlTTTBDzYdkhKjXe/LU1Bwt6iUpJjeKPh/m6sml7PJJalhRV/hLWC+AW2LMz61T0fQJLGsRhXXnUDarHRCstPexOQL7Z3ULPHpuUSGTQK/Q9rwjYjhDdICAE=
  file:
    - $RELEASES_PATH/snapshot/lclip_windows_386.zip
    - $RELEASES_PATH/snapshot/lclip_windows_amd64.zip
    - $RELEASES_PATH/snapshot/lclip_darwin_386.zip
    - $RELEASES_PATH/snapshot/lclip_darwin_amd64.zip
    - $RELEASES_PATH/snapshot/lclip_linux_386.tar.gz
    - $RELEASES_PATH/snapshot/lclip_linux_amd64.tar.gz
    - $RELEASES_PATH/snapshot/lclip_linux_arm.tar.gz
  on:
    repo: kusabashira/lclip
    tags: true
